### ISSUE TITLE
Quotes around search string

### ISSUE THREAD

**Issue by pribilinskiy** [anephew/brackets-zeal#2]
Search is not performed because Zeal obtains the query with unnecessary single quotes
![3kol5gz 1](https://cloud.githubusercontent.com/assets/3078595/5061911/0b5b6e04-6db5-11e4-974a-289dfbfb20ed.png)

**Comment by GandalfTheCoder** [comment]
Pull request submitted with fix for this.

**Comment by FlouksBerlin** [comment]
Still not fixed? :/

**Comment by GandalfTheCoder** [comment]
Not sure why, but my pull request was denied. Looks like they don't want it
fixed.

Nathan

**Comment by g1ps** [comment]
Thanks for the fix. I applied it to my local copy and it works just fine. Please re-submit your pull request, it's cleearly needed.

Cheers.

**Comment by abdelouahabb** [comment]
confirmed the issue here.

**Comment by casterle** [comment]
g1ps, would you please post the code/instructions to fix this issue here?

**Comment by Xhynk** [comment]
@casterle - In the <os:>\Users\<user>\AppData\Roaming\Brackets\extensions\user\anephew.brackets-zeal\node folder is the ZealDomain.js file.

Change line 26 from:
`    child_process.exec("zeal --query '" + str + "'", function (error, stdout, stderr) {`
- to -
`    child_process.exec("zeal --query " + str, function (error, stdout, stderr) {`

You see I've just removed the single quotes from that `.exec` function.

**Comment by casterle** [comment]
Thank you!
